/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('./../components/ui/ElAlert.vue')['default']
    ElButton: typeof import('./../components/ui/ElButton.vue')['default']
    ElDivider: typeof import('./../components/ui/ElDivider.vue')['default']
    ElDrawer: typeof import('./../components/ui/ElDrawer.vue')['default']
    ElEmpty: typeof import('./../components/ui/ElEmpty.vue')['default']
    ElIcon: typeof import('./../components/ui/ElIcon.vue')['default']
    ElInput: typeof import('./../components/ui/ElInput.vue')['default']
    ElOption: typeof import('./../components/ui/ElOption.vue')['default']
    ElSelect: typeof import('./../components/ui/ElSelect.vue')['default']
    ElTabPane: typeof import('./../components/ui/ElTabPane.vue')['default']
    ElTabs: typeof import('./../components/ui/ElTabs.vue')['default']
    ElTag: typeof import('./../components/ui/ElTag.vue')['default']
    ElTooltip: typeof import('./../components/ui/ElTooltip.vue')['default']
    ErrorNotice: typeof import('./../components/common/ErrorNotice.vue')['default']
    WindowFrame: typeof import('./../components/layout/WindowFrame.vue')['default']
    WindowHeaderBar: typeof import('./../components/layout/WindowHeaderBar.vue')['default']
  }
}
